import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Because of Maths",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
      appearance={{
        layout: {
          socialButtonsVariant: "iconButton",
          logoImageUrl:'/logo.svg'
        },
        variables: {
          colorPrimary: "#FDD7BB",
          colorText:'#000',
          colorTextOnPrimaryBackground: "#000"
        },
      }}
      >
        <body className={inter.className}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
