import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Footer from "@/components/shared/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Because of Maths",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        appearance={{
          layout: {
            socialButtonsVariant: "iconButton",
            logoImageUrl: "/logo.svg",
          },
          variables: {
            colorPrimary: "#fc9549",
            colorText: "#000",
            colorTextOnPrimaryBackground: "#000",
          },
        }}
      >
        <body className={roboto.className}>
          {children}
          <Footer />
        </body>
      </ClerkProvider>
    </html>
  );
}
